language: node_js
sudo: enabled
node_js:
  - "10"
script:
  - npm run build
after_script:


cache:
  directories:
  - node_modules

deploy:
  - provider: npm
    skip_cleanup: true
    email: heifade@126.com
    api_key: $NPM_TOKEN
    on:
      branch: master
      repo: heifade/happywork-config


